CXX = /c/msys64/ucrt64/bin/g++.exe
CXXFLAGS = -std=c++17 -Wall -Wextra -pedantic

TARGET = test_map.exe
SRC = test_map.cpp

all: $(TARGET)

$(TARGET): $(SRC)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(SRC)

run: $(TARGET)
	./$(TARGET)

clean:
	rm -f $(TARGET)
